//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        public Workout()
        {
            this.Links = new HashSet<Link>();
        }
    
        public int WorkoutID { get; set; }
        public string Name { get; set; }
        public string BodyPart { get; set; }
        public string Intensity { get; set; }
        public int Reps { get; set; }
        public int Setts { get; set; }
        public System.DateTime WorkoutDate { get; set; }
    
        public virtual ICollection<Link> Links { get; set; }
    }
}
